### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by dashboarddeluxe** [Himmlisch-Studios/amber#1]
Hi Team,

I appreciate that your team has shared this code. This has amazing potential to easily incorporate Tailwind CSS in Grav, Wordpress and Joomla. Right now I am trying to use it in Grav.

From my understanding of a "component library theme" what I did was I placed all the files in a folder named "amber" and placed it in /user/themes. Unfortunately I don't see it as a theme that can be selected.

In Grav, where do I place the files?

Thanks in advance.

Regards,

Jon

**Comment by LuanHimmlisch** [comment]
@dashboarddeluxe hello and sorry for the delayed response.

This is the public repository of the in-house component library we're developing. This public repository only contains the assets such as stylesheets and scripts needed for the library, no theme is hosted here since this is an in-house library on development that we will potentially offer to our clients.

Thanks for the comments, if you ever need a website be sure to contact us via email at [web@himmlisch.com.mx](mailto:web@himmlisch.com.mx)
